from heroku_web_autoscale.backends.notification.console import ConsoleBackend
from heroku_web_autoscale.backends.notification.django_email import DjangoEmailBackend
from heroku_web_autoscale.backends.notification.logger import LoggerBackend
from heroku_web_autoscale.backends.notification.test import TestBackend