from autoscalebot.backends.notification.console import ConsoleBackend
from autoscalebot.backends.notification.django_email import DjangoEmailBackend
from autoscalebot.backends.notification.logger import LoggerBackend
from autoscalebot.backends.notification.test import TestBackend